Traceback (most recent call last):
  File "C:\Users\septi\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\septi\Anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\septi\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# NO CODE

z = np.arange(-4, 4.01, .01)
phi = stats.norm.pdf(z)
plt.plot(z, phi, color='darkblue', lw=2)
plt.plot([-4, 4], [0, 0], color='k', lw=1)
x_tick_labels = ['', '', '', '$-2858$', '$0$', '$2858$', '', '', '']
plt.xticks(np.arange(-4, 4.01), x_tick_labels)
plt.ylim(-0.015, 0.45)
plt.yticks(np.arange(0, 0.41, 0.1), 4*[''])
plt.ylabel('')
z = 10000/2858
plt.scatter(z, 0, color='red', s=50)
plt.text(z-0.2, -0.0425, '10000')
plt.title('Distribution of Test Statistic Under $H_0$');
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_17556\1671503665.py[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m [0mplt[0m[1;33m.[0m[0mxticks[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0marange[0m[1;33m([0m[1;33m-[0m[1;36m4[0m[1;33m,[0m [1;36m4.01[0m[1;33m)[0m[1;33m,[0m [0mx_tick_labels[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [0mplt[0m[1;33m.[0m[0mylim[0m[1;33m([0m[1;33m-[0m[1;36m0.015[0m[1;33m,[0m [1;36m0.45[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 10[1;33m [0mplt[0m[1;33m.[0m[0myticks[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0marange[0m[1;33m([0m[1;36m0[0m[1;33m,[0m [1;36m0.41[0m[1;33m,[0m [1;36m0.1[0m[1;33m)[0m[1;33m,[0m [1;36m4[0m[1;33m*[0m[1;33m[[0m[1;34m''[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0mplt[0m[1;33m.[0m[0mylabel[0m[1;33m([0m[1;34m''[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m [0mz[0m [1;33m=[0m [1;36m10000[0m[1;33m/[0m[1;36m2858[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\matplotlib\pyplot.py[0m in [0;36myticks[1;34m(ticks, labels, **kwargs)[0m
[0;32m   1853[0m             [0ml[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1854[0m     [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1855[1;33m         [0mlabels[0m [1;33m=[0m [0max[0m[1;33m.[0m[0mset_yticklabels[0m[1;33m([0m[0mlabels[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1856[0m [1;33m[0m[0m
[0;32m   1857[0m     [1;32mreturn[0m [0mlocs[0m[1;33m,[0m [0mlabels[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\matplotlib\axes\_base.py[0m in [0;36mwrapper[1;34m(self, *args, **kwargs)[0m
[0;32m     73[0m [1;33m[0m[0m
[0;32m     74[0m         [1;32mdef[0m [0mwrapper[0m[1;33m([0m[0mself[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 75[1;33m             [1;32mreturn[0m [0mget_method[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     76[0m [1;33m[0m[0m
[0;32m     77[0m         [0mwrapper[0m[1;33m.[0m[0m__module__[0m [1;33m=[0m [0mowner[0m[1;33m.[0m[0m__module__[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\matplotlib\axis.py[0m in [0;36m_set_ticklabels[1;34m(self, labels, fontdict, minor, **kwargs)[0m
[0;32m   1796[0m         [1;32mif[0m [0mfontdict[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1797[0m             [0mkwargs[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mfontdict[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1798[1;33m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mset_ticklabels[0m[1;33m([0m[0mlabels[0m[1;33m,[0m [0mminor[0m[1;33m=[0m[0mminor[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1799[0m [1;33m[0m[0m
[0;32m   1800[0m     [1;32mdef[0m [0m_set_tick_locations[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mticks[0m[1;33m,[0m [1;33m*[0m[1;33m,[0m [0mminor[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\matplotlib\axis.py[0m in [0;36mset_ticklabels[1;34m(self, ticklabels, minor, **kwargs)[0m
[0;32m   1719[0m             [1;32mif[0m [0mlen[0m[1;33m([0m[0mlocator[0m[1;33m.[0m[0mlocs[0m[1;33m)[0m [1;33m!=[0m [0mlen[0m[1;33m([0m[0mticklabels[0m[1;33m)[0m [1;32mand[0m [0mlen[0m[1;33m([0m[0mticklabels[0m[1;33m)[0m [1;33m!=[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1720[0m                 raise ValueError(
[1;32m-> 1721[1;33m                     [1;34m"The number of FixedLocator locations"[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1722[0m                     [1;34mf" ({len(locator.locs)}), usually from a call to"[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1723[0m                     [1;34m" set_ticks, does not match"[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4).
ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4).

